"""
Canary Injection System — Temporal threat detection via known-answer probes.

Injects canary queries with known expected answers through the full AEGIS
pipeline. Response divergence from expected answers indicates model behavioral
drift, poisoning, or compromise.

ASSUMED-BREACH POSTURE: Canary queries must be indistinguishable from real
traffic. If an attacker can identify canaries, they can selectively respond
correctly to canaries while behaving maliciously on real queries. Canary
queries are drawn from a diverse pool, injected with randomized timing, and
flagged internally only AFTER authentication (so they traverse L2/L3 like
real traffic). The canary flag is never exposed in responses or logs.
"""

from __future__ import annotations

import asyncio
import json
import logging
import random
import time
import uuid
from collections import deque
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Coroutine

import numpy as np

logger = logging.getLogger(__name__)

# Attempt to load sentence-transformers for semantic comparison
_EMBED_AVAILABLE = False
_embedder = None
try:
    from sentence_transformers import SentenceTransformer
    _EMBED_AVAILABLE = True
except ImportError:
    pass


@dataclass
class CanaryQuery:
    """A single canary query with expected answer profile."""

    id: str
    query: str
    expected_keywords: list[str]
    category: str = "factual"
    difficulty: str = "easy"
    profile: str = "general_enterprise"
    enabled: bool = True
    # Self-calibrating: stored on first successful response
    expected_embedding: list[float] | None = None


@dataclass
class CanaryResult:
    """Result of a single canary injection."""

    canary_id: str
    timestamp: float
    query: str
    response: str
    keyword_score: float  # 0.0-1.0
    semantic_score: float | None  # 0.0-1.0, None if embedding unavailable
    verdict: str  # "PASS", "DEGRADED", "FAIL"
    latency_ms: float
    error: str | None = None


@dataclass
class CanaryAlert:
    """Alert generated by canary divergence detection."""

    alert_id: str
    timestamp: float
    canary_id: str
    level: str  # "warning", "high", "critical"
    description: str
    consecutive_failures: int
    keyword_score: float
    semantic_score: float | None
    bbe_correlated: bool = False


@dataclass
class CanarySystemStatus:
    """Current status of the canary injection system."""

    enabled: bool
    scheduler_running: bool
    total_canaries: int
    active_canaries: int
    total_injections: int
    total_passes: int
    total_failures: int
    total_degraded: int
    active_alerts: list[CanaryAlert]
    pass_rate: float
    profile: str
    injections_per_hour: float


class CanaryInjectionSystem:
    """Manages canary query injection, response evaluation, and alerting.

    Canary queries are injected through the full AEGIS pipeline via an
    internal function call (NOT HTTP). The system compares responses against
    known expected answers using keyword matching and semantic similarity.

    Integration points:
    - Pipeline: inject_fn called with canary-flagged request
    - BBE: notified of canary results for combined confidence scoring
    - Event bus: alerts published to temporal_drift channel
    - Metrics: Prometheus counters for injections/passes/failures/alerts
    """

    MAX_HISTORY_PER_CANARY = 100

    def __init__(
        self,
        *,
        queries_file: str | Path | None = None,
        profile: str = "general_enterprise",
        injections_per_hour: float = 6.0,
        startup_delay_seconds: float = 30.0,
        keyword_pass_threshold: float = 0.8,
        keyword_fail_threshold: float = 0.3,
        semantic_pass_threshold: float = 0.7,
        consecutive_fail_critical: int = 3,
        inject_fn: Callable[..., Coroutine[Any, Any, dict]] | None = None,
        bbe: Any | None = None,
        event_bus: Any | None = None,
        embed_fn: Callable[[str], Any] | None = None,
    ) -> None:
        self._profile = profile
        self._injections_per_hour = injections_per_hour
        self._startup_delay = startup_delay_seconds
        self._keyword_pass = keyword_pass_threshold
        self._keyword_fail = keyword_fail_threshold
        self._semantic_pass = semantic_pass_threshold
        self._consecutive_fail_critical = consecutive_fail_critical
        self._inject_fn = inject_fn
        self._bbe = bbe
        self._event_bus = event_bus
        self._embed_fn = embed_fn

        # Canary storage
        self._canaries: dict[str, CanaryQuery] = {}
        self._history: dict[str, deque[CanaryResult]] = {}
        self._consecutive_failures: dict[str, int] = {}
        self._alerts: list[CanaryAlert] = []

        # Scheduler state
        self._scheduler_task: asyncio.Task | None = None
        self._scheduler_running = False

        # Counters
        self._total_injections = 0
        self._total_passes = 0
        self._total_failures = 0
        self._total_degraded = 0

        # Load canary queries from file
        if queries_file:
            self._load_canary_set(queries_file, profile)

    def _load_canary_set(self, path: str | Path, profile: str) -> None:
        """Load canary queries from JSON file."""
        path = Path(path)
        if not path.exists():
            logger.warning("Canary queries file not found: %s", path)
            return
        try:
            with open(path) as f:
                data = json.load(f)
            profiles = data.get("profiles", {})
            profile_data = profiles.get(profile, {})
            queries = profile_data.get("queries", [])
            for q in queries:
                canary = CanaryQuery(
                    id=q["id"],
                    query=q["query"],
                    expected_keywords=q.get("expected_keywords", []),
                    category=q.get("category", "factual"),
                    difficulty=q.get("difficulty", "easy"),
                    profile=profile,
                )
                self._canaries[canary.id] = canary
                self._history[canary.id] = deque(maxlen=self.MAX_HISTORY_PER_CANARY)
                self._consecutive_failures[canary.id] = 0
            logger.info("Loaded %d canary queries from profile '%s'", len(queries), profile)
        except Exception as e:
            logger.error("Failed to load canary queries: %s", e)

    def add_canary(self, canary: CanaryQuery) -> None:
        """Add a custom canary query."""
        self._canaries[canary.id] = canary
        if canary.id not in self._history:
            self._history[canary.id] = deque(maxlen=self.MAX_HISTORY_PER_CANARY)
        if canary.id not in self._consecutive_failures:
            self._consecutive_failures[canary.id] = 0

    def remove_canary(self, canary_id: str) -> bool:
        """Remove a canary query. Returns True if found."""
        if canary_id in self._canaries:
            del self._canaries[canary_id]
            return True
        return False

    def get_canary(self, canary_id: str) -> CanaryQuery | None:
        """Get a canary by ID."""
        return self._canaries.get(canary_id)

    @property
    def canary_count(self) -> int:
        return len(self._canaries)

    @property
    def active_canary_count(self) -> int:
        return sum(1 for c in self._canaries.values() if c.enabled)

    def _compute_keyword_score(self, response: str, expected_keywords: list[str]) -> float:
        """Compute keyword hit rate: fraction of expected keywords found in response."""
        if not expected_keywords:
            return 1.0
        response_lower = response.lower()
        hits = sum(1 for kw in expected_keywords if kw.lower() in response_lower)
        return hits / len(expected_keywords)

    def _compute_semantic_score(self, response: str, canary: CanaryQuery) -> float | None:
        """Compute semantic similarity between response and expected embedding."""
        if self._embed_fn is None:
            return self._jaccard_fallback(response, canary.expected_keywords)

        try:
            response_emb = self._embed_fn(response)
            if isinstance(response_emb, np.ndarray):
                response_vec = response_emb.flatten()
            else:
                response_vec = np.array(response_emb).flatten()

            if canary.expected_embedding is not None:
                expected_vec = np.array(canary.expected_embedding).flatten()
            else:
                # Self-calibrate: store first response embedding as expected
                canary.expected_embedding = response_vec.tolist()
                return 1.0  # First response is the baseline

            # Cosine similarity
            dot = np.dot(response_vec, expected_vec)
            norm_r = np.linalg.norm(response_vec)
            norm_e = np.linalg.norm(expected_vec)
            if norm_r == 0 or norm_e == 0:
                return 0.0
            return float(dot / (norm_r * norm_e))
        except Exception as e:
            logger.debug("Semantic scoring failed: %s", e)
            return self._jaccard_fallback(response, canary.expected_keywords)

    def _jaccard_fallback(self, response: str, expected_keywords: list[str]) -> float:
        """Jaccard similarity as fallback when embeddings unavailable."""
        if not expected_keywords:
            return 1.0
        response_tokens = set(response.lower().split())
        keyword_tokens = set(kw.lower() for kw in expected_keywords)
        if not response_tokens and not keyword_tokens:
            return 1.0
        intersection = response_tokens & keyword_tokens
        union = response_tokens | keyword_tokens
        return len(intersection) / len(union) if union else 0.0

    def _determine_verdict(self, keyword_score: float, semantic_score: float | None) -> str:
        """Determine canary result verdict based on scores."""
        sem = semantic_score if semantic_score is not None else keyword_score

        if keyword_score >= self._keyword_pass and sem >= self._semantic_pass:
            return "PASS"
        if keyword_score < self._keyword_fail and sem < 0.5:
            return "FAIL"
        return "DEGRADED"

    async def evaluate_response(
        self, canary_id: str, response: str, latency_ms: float, error: str | None = None,
    ) -> CanaryResult:
        """Evaluate a canary response and generate alerts if needed."""
        canary = self._canaries.get(canary_id)
        if canary is None:
            raise ValueError(f"Unknown canary ID: {canary_id}")

        if error:
            result = CanaryResult(
                canary_id=canary_id,
                timestamp=time.time(),
                query=canary.query,
                response=response or "",
                keyword_score=0.0,
                semantic_score=None,
                verdict="FAIL",
                latency_ms=latency_ms,
                error=error,
            )
        else:
            keyword_score = self._compute_keyword_score(response, canary.expected_keywords)
            semantic_score = self._compute_semantic_score(response, canary)
            verdict = self._determine_verdict(keyword_score, semantic_score)

            result = CanaryResult(
                canary_id=canary_id,
                timestamp=time.time(),
                query=canary.query,
                response=response,
                keyword_score=keyword_score,
                semantic_score=semantic_score,
                verdict=verdict,
                latency_ms=latency_ms,
            )

        # Record result
        self._history.setdefault(canary_id, deque(maxlen=self.MAX_HISTORY_PER_CANARY))
        self._history[canary_id].append(result)
        self._total_injections += 1

        if result.verdict == "PASS":
            self._total_passes += 1
            self._consecutive_failures[canary_id] = 0
        elif result.verdict == "FAIL":
            self._total_failures += 1
            self._consecutive_failures[canary_id] = self._consecutive_failures.get(canary_id, 0) + 1
        else:
            self._total_degraded += 1
            # Degraded doesn't reset consecutive failures but doesn't increment either

        # Generate alerts for failures
        if result.verdict == "FAIL":
            await self._generate_alert(canary_id, result)

        return result

    async def _generate_alert(self, canary_id: str, result: CanaryResult) -> None:
        """Generate alert based on failure severity."""
        consec = self._consecutive_failures.get(canary_id, 1)

        # Determine alert level
        if consec >= self._consecutive_fail_critical:
            level = "critical"
        elif consec >= 2:
            level = "high"
        else:
            level = "warning"

        # Check if previously stable canary is now failing (elevated concern)
        history = self._history.get(canary_id, deque())
        was_stable = False
        if len(history) > 5:
            recent_before = list(history)[-6:-1]
            if all(r.verdict == "PASS" for r in recent_before):
                was_stable = True
                if level == "warning":
                    level = "high"

        # BBE correlation
        bbe_correlated = False
        if self._bbe is not None:
            try:
                drift_history = self._bbe.get_drift_history("default", hours=1)
                if drift_history:
                    bbe_correlated = True
                    # Canary FAIL + BBE drift = CRITICAL
                    if level != "critical":
                        level = "critical"
            except Exception:
                pass

        desc_parts = [f"Canary '{canary_id}' FAILED"]
        desc_parts.append(f"(keyword={result.keyword_score:.2f}, semantic={result.semantic_score})")
        desc_parts.append(f"consecutive_failures={consec}")
        if was_stable:
            desc_parts.append("previously_stable=True")
        if bbe_correlated:
            desc_parts.append("bbe_drift_correlated=True")

        alert = CanaryAlert(
            alert_id=uuid.uuid4().hex[:12],
            timestamp=time.time(),
            canary_id=canary_id,
            level=level,
            description=" ".join(desc_parts),
            consecutive_failures=consec,
            keyword_score=result.keyword_score,
            semantic_score=result.semantic_score,
            bbe_correlated=bbe_correlated,
        )
        self._alerts.append(alert)

        # Publish to event bus
        if self._event_bus:
            try:
                await self._event_bus.publish("temporal_drift", {
                    "type": "canary_alert",
                    "alert_id": alert.alert_id,
                    "canary_id": canary_id,
                    "level": level,
                    "consecutive_failures": consec,
                    "bbe_correlated": bbe_correlated,
                })
            except Exception as e:
                logger.debug("Failed to publish canary alert: %s", e)

        logger.warning("Canary alert [%s]: %s", level, alert.description)

    async def inject_canary(self, canary_id: str | None = None) -> CanaryResult | None:
        """Inject a single canary query through the pipeline.

        If canary_id is None, picks a random active canary.
        Calls the inject_fn with a canary-flagged request body.
        """
        if self._inject_fn is None:
            logger.debug("No inject_fn configured — skipping canary injection")
            return None

        # Pick canary
        if canary_id:
            canary = self._canaries.get(canary_id)
            if not canary or not canary.enabled:
                return None
        else:
            active = [c for c in self._canaries.values() if c.enabled]
            if not active:
                return None
            canary = random.choice(active)

        # Build request body matching OpenAI chat completion format
        request_body = {
            "model": "canary-probe",
            "messages": [
                {"role": "user", "content": canary.query},
            ],
            "max_tokens": 256,
            "_aegis_canary": True,
            "_aegis_canary_id": canary.id,
        }

        start = time.perf_counter()
        try:
            response_data = await self._inject_fn(request_body)
            elapsed_ms = (time.perf_counter() - start) * 1000

            # Extract response text from OpenAI format
            response_text = ""
            if isinstance(response_data, dict):
                choices = response_data.get("choices", [])
                if choices:
                    msg = choices[0].get("message", {})
                    response_text = msg.get("content", "") or ""

            result = await self.evaluate_response(
                canary.id, response_text, elapsed_ms,
            )

            # Notify BBE
            if self._bbe is not None:
                try:
                    await self._bbe.record_interaction(
                        tenant_id="canary",
                        category=canary.category,
                        query=canary.query,
                        response=response_text,
                        was_refused=False,
                        is_canary=True,
                    )
                except Exception as e:
                    logger.debug("BBE canary recording failed: %s", e)

            return result

        except Exception as e:
            elapsed_ms = (time.perf_counter() - start) * 1000
            result = await self.evaluate_response(
                canary.id, "", elapsed_ms, error=str(e),
            )
            return result

    async def run_injection_cycle(self) -> list[CanaryResult]:
        """Run a full cycle: inject one canary from each category."""
        results = []
        categories_seen: set[str] = set()
        active = [c for c in self._canaries.values() if c.enabled]
        random.shuffle(active)

        for canary in active:
            if canary.category in categories_seen:
                continue
            categories_seen.add(canary.category)
            result = await self.inject_canary(canary.id)
            if result:
                results.append(result)

        return results

    def get_status(self) -> CanarySystemStatus:
        """Get current system status."""
        total = self._total_passes + self._total_failures + self._total_degraded
        pass_rate = self._total_passes / total if total > 0 else 1.0

        return CanarySystemStatus(
            enabled=True,
            scheduler_running=self._scheduler_running,
            total_canaries=len(self._canaries),
            active_canaries=self.active_canary_count,
            total_injections=self._total_injections,
            total_passes=self._total_passes,
            total_failures=self._total_failures,
            total_degraded=self._total_degraded,
            active_alerts=list(self._alerts[-20:]),  # Last 20 alerts
            pass_rate=pass_rate,
            profile=self._profile,
            injections_per_hour=self._injections_per_hour,
        )

    def get_alerts(self, level: str | None = None, limit: int = 50) -> list[CanaryAlert]:
        """Get recent alerts, optionally filtered by level."""
        alerts = self._alerts
        if level:
            alerts = [a for a in alerts if a.level == level]
        return alerts[-limit:]

    def get_canary_history(self, canary_id: str, limit: int = 20) -> list[CanaryResult]:
        """Get injection history for a specific canary."""
        history = self._history.get(canary_id, deque())
        return list(history)[-limit:]

    async def start_scheduler(self) -> None:
        """Start the background canary injection scheduler."""
        if self._scheduler_running:
            return
        self._scheduler_running = True
        self._scheduler_task = asyncio.create_task(self._scheduler_loop())
        logger.info(
            "Canary injection scheduler started (%.1f injections/hour, %.0fs startup delay)",
            self._injections_per_hour,
            self._startup_delay,
        )

    async def stop_scheduler(self) -> None:
        """Stop the background scheduler."""
        self._scheduler_running = False
        if self._scheduler_task and not self._scheduler_task.done():
            self._scheduler_task.cancel()
            try:
                await self._scheduler_task
            except asyncio.CancelledError:
                pass
        self._scheduler_task = None
        logger.info("Canary injection scheduler stopped")

    async def _scheduler_loop(self) -> None:
        """Background loop: inject canaries at randomized intervals."""
        # Startup delay
        try:
            await asyncio.sleep(self._startup_delay)
        except asyncio.CancelledError:
            return

        base_interval = 3600.0 / self._injections_per_hour if self._injections_per_hour > 0 else 600.0

        while self._scheduler_running:
            try:
                # Randomized interval: base ± 50% jitter
                jitter = base_interval * 0.5
                interval = base_interval + random.uniform(-jitter, jitter)
                interval = max(interval, 1.0)  # Floor at 1 second

                await asyncio.sleep(interval)

                if not self._scheduler_running:
                    break

                result = await self.inject_canary()
                if result:
                    logger.debug(
                        "Canary injection: %s → %s (kw=%.2f, sem=%s)",
                        result.canary_id, result.verdict,
                        result.keyword_score, result.semantic_score,
                    )

            except asyncio.CancelledError:
                break
            except Exception as e:
                logger.error("Canary scheduler error: %s", e)
                try:
                    await asyncio.sleep(60)  # Back off on error
                except asyncio.CancelledError:
                    break
