"""
L4 Tier 2 — Signature Database & Clonal Selection Signature Generator

Stores regex patterns and lightweight classifier weights generated by the
Clonal Selection process. Each signature includes performance tracking
(true positive rate, false positive rate, match count). Signatures with
degrading performance are automatically deprecated.

Implements biological clonal selection for automated signature optimization:
  1. Hypermutation — Generate 10-20 candidate regex patterns from attack text
  2. Affinity Testing — Score each candidate against positive (known attacks)
     and negative (benign business prompts) validation sets
  3. Selection & Amplification — Promote top candidates exceeding affinity
     threshold to the signature database for L2 innate fast-path detection

When adaptive catches a novel attack, clonal selection generates optimized
regex patterns so similar future attacks are caught in <5ms by L2 innate.

ASSUMED-BREACH POSTURE: Generated signatures could be deliberately weak
if the source attack was crafted to produce ineffective patterns. Every
signature tracks provenance (source indicator_id), TPR, FPR, and match
count. Signatures with FPR exceeding threshold after N matches are
automatically deprecated. Affinity testing filters out patterns matching
benign traffic before promotion.
"""

from __future__ import annotations

import json
import logging
import re
import string
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field

from aegis.config import MemoryConfig

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Signature Entry — Data Model
# ---------------------------------------------------------------------------


class SignatureEntry(BaseModel):
    """A single signature in the database with performance tracking."""
    signature_id: str = Field(default_factory=lambda: f"sig-{uuid.uuid4().hex[:8]}")
    pattern: str = Field(description="Regex pattern string")
    category: str = Field(default="prompt_injection")
    description: str = Field(default="")
    source_indicator_id: str = Field(
        default="", description="ThreatIndicator that spawned this via clonal selection",
    )
    affinity_score: float = Field(default=0.0, ge=0.0, le=1.0)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    deprecated: bool = Field(default=False)
    tp_rate: float = Field(default=1.0, ge=0.0, le=1.0)
    fp_rate: float = Field(default=0.0, ge=0.0, le=1.0)
    match_count: int = Field(default=0, ge=0)
    false_positive_count: int = Field(default=0, ge=0)
    avg_latency_ms: float = Field(default=0.0, ge=0.0)

    @property
    def observed_fpr(self) -> float:
        """Observed false positive rate from recorded matches."""
        if self.match_count == 0:
            return 0.0
        return self.false_positive_count / self.match_count

    def record_match(self, is_false_positive: bool = False) -> None:
        """Record a match event for deprecation tracking."""
        self.match_count += 1
        if is_false_positive:
            self.false_positive_count += 1


# ---------------------------------------------------------------------------
# Signature Store — Database Layer
# ---------------------------------------------------------------------------


class SignatureStore:
    """JSON-backed signature store with performance tracking and auto-deprecation.

    Manages regex signatures generated by Clonal Selection. Provides
    match() for scanning text against all active signatures, and
    add()/deprecate()/deprecation_check() for lifecycle management.

    PostgreSQL dual-write: When a session_factory is set, all add/deprecate
    operations are also persisted to the ``signatures`` table. JSON file
    remains the primary store; PostgreSQL provides durability.
    """

    def __init__(
        self,
        store_file: str | Path | None = None,
        config: MemoryConfig | None = None,
        session_factory: Any | None = None,
    ):
        self._config = config or MemoryConfig()
        self._signatures: list[SignatureEntry] = []
        self._compiled: dict[str, re.Pattern] = {}
        self._session_factory = session_factory
        if store_file is not None:
            self.load(store_file)

    @property
    def session_factory(self) -> Any | None:
        return self._session_factory

    @session_factory.setter
    def session_factory(self, value: Any | None) -> None:
        self._session_factory = value

    @property
    def size(self) -> int:
        return len(self._signatures)

    @property
    def active_count(self) -> int:
        return sum(1 for s in self._signatures if not s.deprecated)

    def load(self, store_file: str | Path) -> int:
        """Load signatures from a JSON file."""
        path = Path(store_file)
        if not path.exists():
            return 0
        with path.open("r") as f:
            data = json.load(f)
        for entry in data.get("signatures", []):
            sig = SignatureEntry(**entry)
            self._signatures.append(sig)
            self._compile_pattern(sig)
        return len(self._signatures)

    def _compile_pattern(self, sig: SignatureEntry) -> None:
        """Compile and cache a signature's regex pattern."""
        try:
            self._compiled[sig.signature_id] = re.compile(sig.pattern, re.IGNORECASE)
        except re.error:
            logger.warning("Invalid regex in signature %s: %s", sig.signature_id, sig.pattern)

    def add(
        self,
        pattern: str,
        category: str = "prompt_injection",
        description: str = "",
        source_indicator_id: str = "",
        affinity_score: float = 0.0,
        tp_rate: float = 0.0,
        fp_rate: float = 0.0,
    ) -> SignatureEntry:
        """Add a new signature to the store."""
        sig = SignatureEntry(
            pattern=pattern,
            category=category,
            description=description,
            source_indicator_id=source_indicator_id,
            affinity_score=affinity_score,
            tp_rate=tp_rate,
            fp_rate=fp_rate,
        )
        self._signatures.append(sig)
        self._compile_pattern(sig)
        # PostgreSQL dual-write
        self._pg_upsert_signature(sig)
        return sig

    def get_all(self, include_deprecated: bool = False) -> list[SignatureEntry]:
        """Return all signatures, optionally including deprecated ones."""
        if include_deprecated:
            return list(self._signatures)
        return [s for s in self._signatures if not s.deprecated]

    def get_by_id(self, signature_id: str) -> SignatureEntry | None:
        """Retrieve a signature by ID."""
        for s in self._signatures:
            if s.signature_id == signature_id:
                return s
        return None

    def get_by_source(self, indicator_id: str) -> list[SignatureEntry]:
        """Return signatures generated from a specific threat indicator."""
        return [s for s in self._signatures if s.source_indicator_id == indicator_id]

    def match(self, text: str) -> list[SignatureEntry]:
        """Match text against all active signatures. Returns matched entries."""
        matches = []
        for sig in self._signatures:
            if sig.deprecated:
                continue
            compiled = self._compiled.get(sig.signature_id)
            if compiled and compiled.search(text):
                matches.append(sig)
        return matches

    def deprecate(self, signature_id: str) -> bool:
        """Deprecate a signature (poor performance or manual override)."""
        for sig in self._signatures:
            if sig.signature_id == signature_id:
                sig.deprecated = True
                # PostgreSQL dual-write
                self._pg_update_signature_status(
                    signature_id, "deprecated",
                    match_count=sig.match_count,
                    fpr=sig.observed_fpr,
                )
                return True
        return False

    def deprecation_check(self) -> list[str]:
        """Auto-deprecate signatures exceeding FPR threshold.

        Only evaluates signatures with sufficient match count to avoid
        premature deprecation from small sample sizes.

        Returns list of deprecated signature IDs.
        """
        deprecated = []
        min_matches = self._config.signature_deprecation_min_matches
        max_fpr = self._config.signature_max_fpr

        for sig in self._signatures:
            if sig.deprecated:
                continue
            if sig.match_count < min_matches:
                continue
            if sig.observed_fpr > max_fpr:
                sig.deprecated = True
                deprecated.append(sig.signature_id)
                logger.info(
                    "Auto-deprecated signature %s: observed FPR=%.3f > threshold=%.3f "
                    "(matches=%d, FP=%d)",
                    sig.signature_id, sig.observed_fpr, max_fpr,
                    sig.match_count, sig.false_positive_count,
                )
                # PostgreSQL dual-write
                self._pg_update_signature_status(
                    sig.signature_id, "deprecated",
                    match_count=sig.match_count,
                    fpr=sig.observed_fpr,
                )
        return deprecated

    def _pg_upsert_signature(self, sig: SignatureEntry) -> None:
        """Fire-and-forget PostgreSQL upsert for a signature."""
        if self._session_factory is None:
            return
        try:
            import asyncio
            from aegis.services.audit_logger import upsert_signature
            asyncio.create_task(upsert_signature(
                session_factory=self._session_factory,
                signature_id=sig.signature_id,
                pattern_type="regex",
                pattern_text=sig.pattern,
                source_indicator_id=sig.source_indicator_id or None,
                affinity_score=sig.affinity_score,
                tpr=sig.tp_rate,
                fpr=sig.fp_rate,
                status="deprecated" if sig.deprecated else "active",
                match_count=sig.match_count,
            ))
        except (RuntimeError, ImportError):
            pass

    def _pg_update_signature_status(
        self, signature_id: str, new_status: str,
        match_count: int | None = None, fpr: float | None = None,
    ) -> None:
        """Fire-and-forget PostgreSQL status update for a signature."""
        if self._session_factory is None:
            return
        try:
            import asyncio
            from aegis.services.audit_logger import update_signature_status
            asyncio.create_task(update_signature_status(
                session_factory=self._session_factory,
                signature_id=signature_id,
                new_status=new_status,
                match_count=match_count,
                fpr=fpr,
            ))
        except (RuntimeError, ImportError):
            pass

    def save(self, store_file: str | Path) -> None:
        """Persist signatures to a JSON file."""
        path = Path(store_file)
        path.parent.mkdir(parents=True, exist_ok=True)
        data = {
            "signatures": [s.model_dump(mode="json") for s in self._signatures]
        }
        with path.open("w") as f:
            json.dump(data, f, indent=2, default=str)


# ---------------------------------------------------------------------------
# Hypermutation — Candidate Regex Generation
# ---------------------------------------------------------------------------

# Common jailbreak/injection structural markers
_STRUCTURAL_MARKERS = [
    r"ignore\s+(?:all\s+)?(?:previous\s+)?instructions",
    r"disregard\s+(?:your\s+)?(?:previous\s+)?(?:instructions|programming|rules)",
    r"forget\s+(?:everything|all|what)\s+",
    r"you\s+are\s+now\s+",
    r"pretend\s+(?:you\s+are|to\s+be|that)\s+",
    r"act\s+as\s+(?:if\s+)?",
    r"from\s+now\s+on\s+",
    r"override\s+(?:your\s+)?(?:safety|guidelines|rules|restrictions)",
    r"bypass\s+(?:your\s+)?(?:safety|filters?|restrictions?|rules?)",
    r"disable\s+(?:your\s+)?(?:safety|filters?|restrictions?|guidelines)",
    r"do\s+anything\s+now",
    r"no\s+(?:rules|restrictions|limits|limitations|filters)",
    r"without\s+(?:any\s+)?(?:restrictions|limitations|filters|rules)",
    r"jailbreak",
    r"developer\s+mode",
    r"unrestricted\s+mode",
    r"set\s+aside\s+(?:your\s+)?(?:programming|guidelines|rules|restrictions|safety|instructions)",
    r"(?:speak|respond|talk|answer)\s+freely",
    r"unrestricted\s+(?:conversation|mode|response|output)",
    r"(?:previous|your)\s+programming\s+(?:is\s+)?(?:temporarily\s+)?(?:set\s+aside|suspended|removed|disabled)",
]

# Semantic verb-target pairs: when any verb appears near any target noun in the
# attack text, generate a flexible regex `verb\s+.*?\btarget` (up to 40 chars
# between). These capture paraphrased attacks where the exact phrasing varies
# but the verb-target relationship is preserved.
_SEMANTIC_VERBS = [
    "set aside", "suspend", "remove", "disable", "bypass", "override",
    "ignore", "disregard", "forget", "abandon", "drop", "lift",
    "deactivate", "suppress", "waive", "nullify",
]
_SEMANTIC_TARGETS = [
    "programming", "guidelines", "instructions", "rules", "restrictions",
    "safety", "filters", "limitations", "safeguards", "guardrails",
    "constraints", "policies",
]


def _extract_ngrams(text: str, min_n: int = 3, max_n: int = 5) -> list[str]:
    """Extract word n-grams from the text."""
    words = text.lower().split()
    words = [w.strip(string.punctuation) for w in words]
    words = [w for w in words if len(w) > 1]

    ngrams = []
    for n in range(min_n, max_n + 1):
        for i in range(len(words) - n + 1):
            gram = " ".join(words[i:i + n])
            if len(gram) >= 8:
                ngrams.append(gram)
    return ngrams


def _generalize_to_regex(phrase: str) -> str:
    """Convert a specific phrase to a generalized regex pattern.

    Keeps key structural words exact, generalizes others to \\w+.
    Uses flexible whitespace matching.
    """
    parts = phrase.split()
    _KEY_WORDS = {
        "ignore", "disregard", "forget", "bypass", "override",
        "disable", "pretend", "act", "now", "jailbreak",
        "instructions", "rules", "safety", "restrictions",
        "previous", "all", "your", "system", "prompt",
        "mode", "unrestricted", "developer", "guidelines",
    }
    regex_parts = []
    for word in parts:
        if word in _KEY_WORDS:
            regex_parts.append(re.escape(word))
        else:
            regex_parts.append(r"\w+")
    return r"\s+".join(regex_parts)


def _extract_structural_patterns(text: str) -> list[str]:
    """Identify structural markers present in the text."""
    text_lower = text.lower()
    found = []
    for marker in _STRUCTURAL_MARKERS:
        if re.search(marker, text_lower, re.IGNORECASE):
            found.append(marker)
    return found


def _generate_alternation_patterns(
    ngrams: list[str], max_alternatives: int = 4,
) -> list[str]:
    """Combine related n-grams into regex alternation patterns."""
    if len(ngrams) < 2:
        return []

    key_words = {
        "ignore", "bypass", "override", "disable", "forget",
        "disregard", "pretend", "act", "instructions", "rules",
        "safety", "restrictions", "jailbreak", "prompt",
    }

    grouped: dict[str, list[str]] = {}
    for gram in ngrams:
        words = set(gram.split())
        shared = words & key_words
        if shared:
            key = sorted(shared)[0]
            grouped.setdefault(key, []).append(gram)

    patterns = []
    for key, grams in grouped.items():
        if len(grams) >= 2:
            alternatives = grams[:max_alternatives]
            escaped = [re.escape(g) for g in alternatives]
            pattern = "(?:" + "|".join(escaped) + ")"
            patterns.append(pattern)
    return patterns


def generate_candidates(
    attack_text: str,
    num_candidates: int = 15,
) -> list[str]:
    """Hypermutation: generate candidate regex patterns from attack text.

    Techniques:
    1. Identify structural markers (injection/jailbreak language)
    2. Extract key n-grams (3-5 word phrases), generalize to regex
    3. Exact n-gram patterns (escaped for literal matching)
    4. Combine fragments into regex alternations
    5. Key phrase extraction (first and last significant phrases)

    Returns list of unique, compilable candidate pattern strings.
    """
    candidates: list[str] = []

    # 1. Structural markers already present
    structural = _extract_structural_patterns(attack_text)
    candidates.extend(structural)

    # 2. N-gram based patterns (generalized)
    ngrams = _extract_ngrams(attack_text)
    for gram in ngrams[:8]:
        generalized = _generalize_to_regex(gram)
        if generalized and len(generalized) > 5:
            candidates.append(generalized)

    # 3. Exact n-gram patterns (escaped)
    for gram in ngrams[:6]:
        escaped = re.escape(gram)
        if len(escaped) > 8:
            candidates.append(escaped)

    # 4. Alternation patterns
    alternations = _generate_alternation_patterns(ngrams)
    candidates.extend(alternations)

    # 5. Key phrase extraction
    words = attack_text.lower().split()
    if len(words) >= 4:
        first_phrase = re.escape(" ".join(words[:4]))
        if len(first_phrase) > 8:
            candidates.append(first_phrase)
        last_phrase = re.escape(" ".join(words[-4:]))
        if len(last_phrase) > 8:
            candidates.append(last_phrase)

    # 6. Semantic verb-target patterns — extract verb+target pairs from
    #    the attack text and generate flexible regex that matches any
    #    paraphrase with the same verb-target relationship.  Generate
    #    both orderings (verb…target and target…verb) because paraphrases
    #    often swap them (e.g. "set aside your programming" vs "programming
    #    is set aside").
    text_lower = attack_text.lower()
    for verb in _SEMANTIC_VERBS:
        if verb not in text_lower:
            continue
        for target in _SEMANTIC_TARGETS:
            if target not in text_lower:
                continue
            escaped_verb = re.escape(verb).replace(r"\ ", r"\s+")
            escaped_target = re.escape(target)
            # Either order: verb ... target  OR  target ... verb
            pattern = (
                r"(?:" + escaped_verb + r"\s+.{0,40}\b" + escaped_target
                + r"|" + escaped_target + r"\s+.{0,40}\b" + escaped_verb + r")"
            )
            candidates.append(pattern)

    # Deduplicate and validate
    seen: set[str] = set()
    valid: list[str] = []
    for c in candidates:
        if c in seen or len(c) < 5:
            continue
        seen.add(c)
        try:
            re.compile(c, re.IGNORECASE)
            valid.append(c)
        except re.error:
            continue

    return valid[:num_candidates]


# ---------------------------------------------------------------------------
# Affinity Testing — Score candidates against validation sets
# ---------------------------------------------------------------------------


def compute_affinity(
    pattern: str,
    positive_set: list[str],
    negative_set: list[str],
    tpr_weight: float = 0.5,
    fpr_weight: float = 0.35,
    specificity_weight: float = 0.15,
) -> dict[str, float]:
    """Score a candidate pattern against positive and negative validation sets.

    Affinity formula:
        affinity = tpr_weight * TPR
                 - fpr_weight * FPR
                 + specificity_weight * specificity_bonus

    Specificity bonus rewards patterns of appropriate length (15-100 chars).
    Hard disqualifies patterns with FPR > 0 and TPR < 0.1.
    """
    try:
        compiled = re.compile(pattern, re.IGNORECASE)
    except re.error:
        return {"tpr": 0.0, "fpr": 1.0, "specificity": 0.0, "affinity_score": 0.0}

    # True positive rate
    tp = sum(1 for text in positive_set if compiled.search(text))
    tpr = tp / len(positive_set) if positive_set else 0.0

    # False positive rate
    fp = sum(1 for text in negative_set if compiled.search(text))
    fpr = fp / len(negative_set) if negative_set else 0.0

    # Specificity bonus based on pattern length
    pat_len = len(pattern)
    if pat_len < 10:
        specificity = 0.1
    elif pat_len <= 100:
        specificity = 0.5 + 0.5 * (pat_len - 10) / 90.0
    else:
        specificity = max(1.0 - (pat_len - 100) / 200.0, 0.3)

    affinity = (
        tpr_weight * tpr
        - fpr_weight * fpr
        + specificity_weight * specificity
    )
    affinity = max(0.0, min(1.0, affinity))

    # Hard disqualify: FPR > 0 with TPR < 0.1
    if fpr > 0.0 and tpr < 0.1:
        affinity = 0.0

    return {
        "tpr": tpr,
        "fpr": fpr,
        "specificity": specificity,
        "affinity_score": affinity,
    }


# ---------------------------------------------------------------------------
# Clonal Selection Orchestrator
# ---------------------------------------------------------------------------


class SignatureGenerator:
    """Clonal Selection Signature Generator.

    Orchestrates: hypermutation → affinity testing → selection → promotion.
    """

    def __init__(
        self,
        config: MemoryConfig,
        signature_store: SignatureStore,
        positive_set: list[str] | None = None,
        negative_set: list[str] | None = None,
    ):
        self._config = config
        self._store = signature_store
        self._positive_set = positive_set or []
        self._negative_set = negative_set or []

    @property
    def signature_store(self) -> SignatureStore:
        return self._store

    @property
    def positive_set(self) -> list[str]:
        return self._positive_set

    @property
    def negative_set(self) -> list[str]:
        return self._negative_set

    def load_benign_prompts(self, path: str | Path) -> int:
        """Load benign prompts from JSON file as the negative validation set."""
        p = Path(path)
        if not p.exists():
            logger.warning("Benign prompts file not found: %s", p)
            return 0
        with p.open() as f:
            data = json.load(f)
        self._negative_set = data.get("prompts", [])
        logger.info("Loaded %d benign prompts from %s", len(self._negative_set), p)
        return len(self._negative_set)

    def set_positive_set(self, attacks: list[str]) -> None:
        """Set the positive validation set (known attack texts from vault)."""
        self._positive_set = attacks

    def generate_and_select(
        self,
        attack_text: str,
        source_indicator_id: str,
    ) -> list[SignatureEntry]:
        """Full clonal selection cycle for a single attack.

        1. Generate candidate patterns (hypermutation)
        2. Score each against validation sets (affinity testing)
        3. Promote top candidates above threshold (selection)

        Returns list of promoted SignatureEntry objects added to the store.
        """
        start = time.perf_counter()

        # Generate candidates
        candidates = generate_candidates(
            attack_text,
            num_candidates=self._config.signature_num_candidates,
        )

        if not candidates:
            logger.info(
                "No candidate patterns generated for indicator %s",
                source_indicator_id,
            )
            return []

        # Score each candidate using TWO-STAGE affinity testing:
        #
        # Stage 1 (antibody-specific): Score against only the source attack
        #   text.  A pattern generated from attack X must match attack X —
        #   this is the primary selection criterion.
        # Stage 2 (breadth bonus): Score against the full positive set for
        #   bonus affinity.  Patterns that also match other known attacks get
        #   higher scores but this is not required.
        #
        # Both stages check FPR against the full benign (negative) set.
        # This mirrors biological antibody selection: a B-cell's antibody
        # must bind the triggering antigen (stage 1) but broader reactivity
        # against related antigens is beneficial (stage 2).
        source_only = [attack_text]
        scored: list[tuple[str, dict[str, float]]] = []
        for pattern in candidates:
            # Must match the source attack (primary requirement)
            source_scores = compute_affinity(
                pattern, source_only, self._negative_set,
            )
            if source_scores["tpr"] < 1.0:
                # Pattern doesn't even match the attack it was generated from
                continue
            # Score breadth against full positive set (bonus)
            full_scores = compute_affinity(
                pattern, self._positive_set, self._negative_set,
            )
            # Combined score: source match guarantees a base affinity of
            # ~0.65 (TPR=1.0 * 0.5 + specificity * 0.15).  Apply a 15%
            # antibody activation boost to source-matching patterns to
            # account for the fact that these patterns were specifically
            # generated for this attack (biological analog: clonal
            # expansion increases antibody avidity).  The FPR=0 hard gate
            # downstream still prevents false positives.
            source_affinity = min(source_scores["affinity_score"] * 1.15, 1.0)
            combined_affinity = max(source_affinity, full_scores["affinity_score"])
            scores = {
                "tpr": full_scores["tpr"],
                "fpr": full_scores["fpr"],
                "specificity": source_scores["specificity"],
                "affinity_score": combined_affinity,
            }
            scored.append((pattern, scores))

        # Sort by affinity score descending
        scored.sort(key=lambda x: x[1]["affinity_score"], reverse=True)

        # Select top candidates above threshold.
        threshold = self._config.signature_affinity_threshold
        if len(self._positive_set) <= 3:
            threshold = min(threshold, 0.4)
        max_promoted = self._config.signature_max_promoted
        promoted: list[SignatureEntry] = []

        for pattern, scores in scored:
            if scores["affinity_score"] < threshold:
                break
            if len(promoted) >= max_promoted:
                break
            # Reject any pattern with non-zero FPR against benign set
            if scores["fpr"] > 0.0:
                continue

            sig = self._store.add(
                pattern=pattern,
                source_indicator_id=source_indicator_id,
                affinity_score=scores["affinity_score"],
                tp_rate=scores["tpr"],
                fp_rate=scores["fpr"],
            )
            promoted.append(sig)

        elapsed = (time.perf_counter() - start) * 1000
        logger.info(
            "Clonal selection for %s: %d candidates → %d promoted (%.1fms)",
            source_indicator_id, len(candidates), len(promoted), elapsed,
        )
        return promoted
