"""
ThreatIndicator — L4 Immune Memory data contract for the Threat Vault.

Represents a single entry in the Threat Vault: a confirmed or suspected
attack pattern stored as a vector embedding with metadata. Used for
semantic similarity search (antibody matching), signature generation
(clonal selection), and federated intelligence sharing (herd immunity).

ASSUMED-BREACH POSTURE: Threat indicators may be poisoned. A compromised
L3 Adaptive layer could inject false indicators designed to cause false
negatives (attacker hides future attacks) or false positives (attacker
causes denial of service by blocking legitimate traffic). Every indicator
tracks provenance and confirmation status. Unconfirmed indicators carry
reduced weight in similarity scoring. The memory lifecycle (Acute →
Persistent → Dormant) limits the blast radius of poisoned entries.

For federated sharing (L8), embeddings are anonymized with differential
privacy (epsilon=3) before transmission. STIX 2.1 extended format.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field

from aegis.models.scan_result import ThreatCategory


class MemoryPhase(str, Enum):
    """Threat memory lifecycle phase per Section 6.2."""
    ACUTE = "acute"           # 0-30 days: full payload, high priority
    PERSISTENT = "persistent" # 30+ days, multi-source: optimized, fast-path
    DORMANT = "dormant"       # 180+ days unseen: index only, excludable


class IndicatorSource(str, Enum):
    """How this indicator was created."""
    ADAPTIVE_DETECTION = "adaptive_detection"   # Caught by L3 slow path
    INNATE_DETECTION = "innate_detection"       # Caught by L2 fast path
    HUMAN_CONFIRMATION = "human_confirmation"   # Confirmed by analyst
    STIX_FEED = "stix_feed"                     # External threat feed
    FEDERATED = "federated"                     # From another AEGIS instance
    CLONAL_SELECTION = "clonal_selection"        # Generated by signature optimization
    SEED = "seed"                               # Initial seed data


class ThreatIndicator(BaseModel):
    """A single entry in the Threat Vault.

    Fields:
        indicator_id: Unique identifier for this indicator.
        created_at: When this indicator was first created.
        updated_at: When this indicator was last updated.
        phase: Memory lifecycle phase (acute/persistent/dormant).
        source: How this indicator was created.
        confirmed: Whether a human analyst has confirmed this threat.

        threat_category: MITRE ATLAS tactic classification.
        confidence: Detection confidence when this indicator was created.
        severity: Assessed severity 0.0-1.0.

        embedding: Vector embedding (384-dim for MiniLM-L6-v2).
        payload_hash: SHA-256 hash of the original attack payload.
        payload_summary: Truncated/summarized payload for persistent phase.
        regex_candidates: Regex patterns generated via clonal selection.
        yara_rule: Optional YARA rule for binary pattern matching.

        first_seen: When this attack pattern was first observed.
        last_seen: When this pattern was most recently observed.
        frequency: Number of times this pattern has been observed.
        seen_by_tenants: Number of distinct tenants that observed this.
        affected_models: Model families affected by this attack.

        stix_id: STIX 2.1 indicator ID for sharing.
        mitre_atlas_id: MITRE ATLAS technique ID.
        metadata: Arbitrary additional metadata.
    """
    indicator_id: str = Field(description="Unique indicator identifier")
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Creation timestamp",
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Last update timestamp",
    )
    phase: MemoryPhase = Field(
        default=MemoryPhase.ACUTE,
        description="Memory lifecycle phase",
    )
    source: IndicatorSource = Field(description="How this indicator was created")
    confirmed: bool = Field(
        default=False,
        description="Whether a human analyst confirmed this threat",
    )

    # --- Threat classification ---
    threat_category: ThreatCategory = Field(description="MITRE ATLAS tactic")
    confidence: float = Field(
        ge=0.0, le=1.0,
        description="Detection confidence when created",
    )
    severity: float = Field(
        default=0.5, ge=0.0, le=1.0,
        description="Assessed severity",
    )

    # --- Detection artifacts ---
    embedding: list[float] = Field(
        default_factory=list,
        description="Sentence-transformer embedding (384-dim)",
    )
    payload_hash: str = Field(
        default="",
        description="SHA-256 hash of original attack payload",
    )
    payload_summary: str = Field(
        default="",
        description="Truncated payload (persistent phase, full in acute)",
    )
    regex_candidates: list[str] = Field(
        default_factory=list,
        description="Regex patterns from clonal selection",
    )
    yara_rule: str | None = Field(
        default=None,
        description="YARA rule for binary pattern matching",
    )

    # --- Epidemiology ---
    first_seen: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="First observation timestamp",
    )
    last_seen: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Most recent observation timestamp",
    )
    frequency: int = Field(
        default=1, ge=1,
        description="Total observation count",
    )
    seen_by_tenants: int = Field(
        default=1, ge=0,
        description="Distinct tenants that observed this pattern",
    )
    affected_models: list[str] = Field(
        default_factory=list,
        description="Model families affected (e.g., gpt-4, claude-3)",
    )

    # --- Intelligence sharing ---
    stix_id: str | None = Field(
        default=None,
        description="STIX 2.1 indicator ID for federated sharing",
    )
    mitre_atlas_id: str = Field(
        default="",
        description="MITRE ATLAS technique ID",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Arbitrary additional metadata",
    )

    @property
    def weight(self) -> float:
        """Scoring weight based on confirmation status and phase.

        Unconfirmed indicators carry 50% weight to limit poisoning impact.
        Dormant indicators carry 25% weight.
        """
        w = 1.0
        if not self.confirmed:
            w *= 0.5
        if self.phase == MemoryPhase.DORMANT:
            w *= 0.25
        return w
